/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dafa Zakhulhaq
 */

import javax.swing.JOptionPane ;
public class Cek extends javax.swing.JFrame {

    String temp = "" ;
    Double br,ti,hi ;
    
    /**
     * Creates new form Cek
     */
    public Cek() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        berat = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        tinggii = new javax.swing.JTextField();
        lk = new javax.swing.JRadioButton();
        pr = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ideal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        saran = new javax.swing.JTextField();
        hasil = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 0));
        getContentPane().setLayout(null);

        jLabel1.setText("Jenis Kelamin");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 140, 70, 40);

        jLabel2.setText("CEK KESEHATAN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 10, 100, 30);

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 50, 50, 30);

        jLabel4.setText("Tinggi");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 80, 50, 30);

        jLabel5.setText("Berat  Badan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 100, 90, 50);
        getContentPane().add(berat);
        berat.setBounds(100, 110, 70, 30);
        getContentPane().add(nama);
        nama.setBounds(100, 50, 210, 30);
        getContentPane().add(tinggii);
        tinggii.setBounds(100, 80, 70, 30);

        buttonGroup1.add(lk);
        lk.setText("Laki");
        lk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lkActionPerformed(evt);
            }
        });
        getContentPane().add(lk);
        lk.setBounds(220, 150, 130, 23);

        buttonGroup1.add(pr);
        pr.setText("Perempuan");
        getContentPane().add(pr);
        pr.setBounds(100, 150, 110, 23);

        jButton2.setText("Hitung");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 180, 90, 30);

        jButton3.setText("Keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(250, 180, 90, 30);

        jLabel6.setText("CM");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 80, 40, 30);
        getContentPane().add(ideal);
        ideal.setBounds(190, 220, 70, 30);

        jLabel7.setText("Hasil Diagnosa Kesehatan ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 250, 150, 30);

        jLabel8.setText("KG");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 120, 40, 20);

        jLabel9.setText("KG");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(270, 220, 50, 30);

        jLabel10.setText("Berat Badan Ideal Anda");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 220, 130, 40);
        getContentPane().add(saran);
        saran.setBounds(10, 320, 380, 30);
        getContentPane().add(hasil);
        hasil.setBounds(10, 280, 380, 30);

        jButton4.setText("Coba Lagi");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(133, 180, 90, 30);

        setBounds(0, 0, 416, 412);
    }// </editor-fold>//GEN-END:initComponents

    private void lkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lkActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        dispose() ;
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (nama.getText().equals("")||berat.getText().equals("")||tinggii.getText().equals(""))
            
            JOptionPane.showMessageDialog(null, "Data Isian Belum Lengkap");
        
        else if (pr.isSelected() || lk.isSelected())
        {
            try{
                
                Proses() ;
            }catch(Exception e){
                
                JOptionPane.showMessageDialog(null, "Masukan Ada Yang Salah");
            }
        
        }
                
        
        

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        nama.setText("");
        berat.setText("");
        tinggii.setText("");
        ideal.setText("");
        saran.setText("");
        hasil.setText("");
        buttonGroup1.clearSelection();
        pr.setSelected(false);
        lk.setSelected(false);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField berat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField hasil;
    private javax.swing.JTextField ideal;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton lk;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton pr;
    private javax.swing.JTextField saran;
    private javax.swing.JTextField tinggii;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        ti = Double.valueOf(tinggii.getText()) ;
        br = Double.valueOf(berat.getText()) ;
        
        if(pr.isSelected())
        {
            hi = (ti - 100) * 1 ;
          
        }else if(lk.isSelected())
        {
            hi = (ti - 104) * 1 ;
            
        }
        temp = Double.toString(hi.intValue()) ;

            if(hi<br)
            {

                ideal.setText(temp);
                hasil.setText(" Maaf " +nama.getText()+" , Sepertinya Anda OverWeight ");
                saran.setText(" Banyaklah berolahraga dan hindari makan ");


            }
            
            else if(hi>br)
            {
            
                ideal.setText(temp);
                hasil.setText(" Maaf " +nama.getText()+" , Sepertinya Anda UnderWeight ");
                saran.setText(" Banyaklah berolahraga dan banyakanlah makan makanan yang mengandung karbohidrat tinggi ");
            
            
            }
            
            else             {
            
                ideal.setText(temp);
                hasil.setText(" Halo " +nama.getText()+" , Sepertinya berat badan anda sudah ideal ");
                saran.setText(" Lanjutkan pola hidup anda yang sehat ini :) ");
            
            
            }
        
        
    }
}
